version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Direct port 80 for production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: vue-portfolio-prod
    # Remove external network dependency for simpler deployment