version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: vue-portfolio
    networks:
      - riknus-networks
      - nginx-proxy_proxy-network

networks:
  riknus-networks:
    driver: bridge
    name: riknus-networks
    external: true
  nginx-proxy_proxy-network:
    external: true